### ISSUE TITLE
(fix): update feature request template

### ISSUE THREAD

**Issue by jmartinn** [StrapexLabs/strapex#33]
### Description
The current feature request template has a bug in the description section causing it to not render properly, along with a restrictive title prefix. This should be fixed to ensure proper functionality of the template.

### Current Limitations

The current template has two key issues:
1. The description section is not rendering at all due to incorrect YAML formatting where the description value is inlined with the markdown header
2. The title prefix '[feat]: ' is too restrictive and doesn't allow for other types of scope

### Proposed Solution

Fix the YAML structure and update the prefix with these specific changes:

```yaml
name: "Feature Request"
description: "Suggest an idea or improvement for the project"
title: '[scope]: '
labels: ['area: request']
body:
  - type: markdown
    attributes:
      value: |
        ### Thanks for taking the time to create a feature request! Please search open/closed issues before submitting, as the issue may have already been reported/addressed.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature description
      description: Tell us about your feature request
      placeholder: 'I think this feature would be great because...'
      value: 'Describe your feature request...'
    validations:
      required: true

# ...rest of the file remains the same
```

### Acceptance Criteria

- [ ] Fix description section rendering by correcting YAML structure
- [ ] Update title prefix to '[scope]: ' for more flexibility
- [ ] Verify description section renders correctly in new issues

### Additional Information

The main motivation for this change is to fix the broken description rendering which affects all new feature requests. The scope prefix update is a small improvement we can include while fixing the bug. Since this is a straightforward template fix, providing the solution in an issue rather than a PR makes more sense for efficiency.
